name: easy_crypt
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  data_table_2: ^2.5.10
  date_format: ^2.0.7
  desktop_drop: ^0.4.4
  dropdown_button2: ^2.3.9
  ffi: ^2.0.1
  file_selector: ^1.0.2
  flutter_riverpod: ^2.4.9
  flutter_rust_bridge: 1.82.6
  flutter:
    sdk: flutter
  isar: ^3.1.0+1  # run `flutter pub run build_runner build` to generate codes
  isar_flutter_libs: ^3.1.0+1
  logging: ^1.2.0
  open_file: ^3.3.2
  path_provider: ^2.1.2
  super_clipboard: ^0.8.2+1
  url_launcher: ^6.2.3
  window_manager: ^0.3.7
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  build_runner_core: ^7.2.9
  ffigen: ^9.0.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets: 
    - assets/images/

  fonts:
    - family: NotoSns
      fonts:
        - asset: assets/fonts/NotoSansSC-Bold.ttf

  