name: easy_crypt
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ffi: ^2.0.1
  file_selector: ^1.0.2
  flutter_riverpod: ^2.4.9
  flutter_rust_bridge: 1.82.6
  logging: ^1.2.0
  window_manager: ^0.3.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner_core: ^7.2.9
  ffigen: ^9.0.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0

flutter:
  uses-material-design: true

  