// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.21.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/crypt.dart';
import 'api/datasource.dart';
import 'api/s3.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.io.dart' if (dart.library.html) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'process/datasource.dart';
import 'process/encrypt.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.initApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.0.0-dev.21';

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> compress(
      {required List<String> paths, required String saveDir, dynamic hint});

  Future<String> decrypt(
      {required String saveDir,
      required String path,
      required String key,
      String? fileType,
      required int fileId,
      dynamic hint});

  Future<String> defaultKey({dynamic hint});

  Future<String> encrypt(
      {required String saveDir,
      required List<EncryptItem> files,
      required String key,
      dynamic hint});

  Future<List<String>> flowPreview(
      {required List<String> operators, dynamic hint});

  Future<bool> isEasyEncryptFile({required String p, dynamic hint});

  Future<String> randomKey({dynamic hint});

  Future<int> addLocalDatasource({required String p, dynamic hint});

  Future<void> addLocalDatasourceWithType(
      {required String p, required DatasourcePreviewType t, dynamic hint});

  Future<int> addS3Datasource(
      {required String endpoint,
      required String bucketname,
      required String accessKey,
      required String sessionKey,
      String? sessionToken,
      required String region,
      dynamic hint});

  Future<void> addS3DatasourceWithType(
      {required String endpoint,
      required String bucketname,
      required String accessKey,
      required String sessionKey,
      String? sessionToken,
      required String region,
      required DatasourcePreviewType t,
      dynamic hint});

  Future<List<Entry>> listObjectsByIndex(
      {required int index, required String p, dynamic hint});

  Future<List<Entry>> listObjectsLeft({required String p, dynamic hint});

  Future<List<Entry>> listObjectsRight({required String p, dynamic hint});

  Future<String> transferBetweenTwoDatasource(
      {required String p,
      required String savePath,
      required bool autoEncrypt,
      dynamic hint});

  Future<void> transferFromLeftToRight(
      {required int leftIndex,
      required int rightIndex,
      required String p,
      required String savePath,
      required bool autoEncrypt,
      dynamic hint});

  Future<bool> checkAccountAvailable(
      {required String endpoint,
      required String bucketname,
      required String accessKey,
      required String sessionKey,
      String? sessionToken,
      required String region,
      dynamic hint});

  Future<void> downloadFromS3(
      {required String p, required String obj, dynamic hint});

  Future<String?> generatePregisnUrl(
      {required String endpoint,
      required String bucketname,
      required String accessKey,
      required String sessionKey,
      String? sessionToken,
      required String region,
      required String obj,
      dynamic hint});

  Future<void> initS3Client(
      {required String endpoint,
      required String bucketname,
      required String accessKey,
      required String sessionKey,
      String? sessionToken,
      required String region,
      dynamic hint});

  Future<List<Entry>> listObjects(
      {required String endpoint,
      required String bucketname,
      required String accessKey,
      required String sessionKey,
      String? sessionToken,
      required String region,
      required String path,
      required bool useGlobal,
      dynamic hint});

  Future<void> uploadToS3(
      {required String p, required String obj, dynamic hint});

  Future<void> uploadToS3WithConfig(
      {required String endpoint,
      required String bucketname,
      required String accessKey,
      required String sessionKey,
      String? sessionToken,
      required String region,
      required String p,
      required String obj,
      dynamic hint});

  String greet({required String name, dynamic hint});

  Future<void> initApp({dynamic hint});

  Stream<String> nativeMessageStream({dynamic hint});

  Future<void> testEncrypt({dynamic hint});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> compress(
      {required List<String> paths, required String saveDir, dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(paths, serializer);
        sse_encode_String(saveDir, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCompressConstMeta,
      argValues: [paths, saveDir],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kCompressConstMeta => const TaskConstMeta(
        debugName: "compress",
        argNames: ["paths", "saveDir"],
      );

  @override
  Future<String> decrypt(
      {required String saveDir,
      required String path,
      required String key,
      String? fileType,
      required int fileId,
      dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(saveDir, serializer);
        sse_encode_String(path, serializer);
        sse_encode_String(key, serializer);
        sse_encode_opt_String(fileType, serializer);
        sse_encode_i_64(fileId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kDecryptConstMeta,
      argValues: [saveDir, path, key, fileType, fileId],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kDecryptConstMeta => const TaskConstMeta(
        debugName: "decrypt",
        argNames: ["saveDir", "path", "key", "fileType", "fileId"],
      );

  @override
  Future<String> defaultKey({dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kDefaultKeyConstMeta,
      argValues: [],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kDefaultKeyConstMeta => const TaskConstMeta(
        debugName: "default_key",
        argNames: [],
      );

  @override
  Future<String> encrypt(
      {required String saveDir,
      required List<EncryptItem> files,
      required String key,
      dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(saveDir, serializer);
        sse_encode_list_encrypt_item(files, serializer);
        sse_encode_String(key, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kEncryptConstMeta,
      argValues: [saveDir, files, key],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kEncryptConstMeta => const TaskConstMeta(
        debugName: "encrypt",
        argNames: ["saveDir", "files", "key"],
      );

  @override
  Future<List<String>> flowPreview(
      {required List<String> operators, dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(operators, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: null,
      ),
      constMeta: kFlowPreviewConstMeta,
      argValues: [operators],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kFlowPreviewConstMeta => const TaskConstMeta(
        debugName: "flow_preview",
        argNames: ["operators"],
      );

  @override
  Future<bool> isEasyEncryptFile({required String p, dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(p, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kIsEasyEncryptFileConstMeta,
      argValues: [p],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kIsEasyEncryptFileConstMeta => const TaskConstMeta(
        debugName: "is_easy_encrypt_file",
        argNames: ["p"],
      );

  @override
  Future<String> randomKey({dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kRandomKeyConstMeta,
      argValues: [],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kRandomKeyConstMeta => const TaskConstMeta(
        debugName: "random_key",
        argNames: [],
      );

  @override
  Future<int> addLocalDatasource({required String p, dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(p, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_i_64,
        decodeErrorData: null,
      ),
      constMeta: kAddLocalDatasourceConstMeta,
      argValues: [p],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kAddLocalDatasourceConstMeta => const TaskConstMeta(
        debugName: "add_local_datasource",
        argNames: ["p"],
      );

  @override
  Future<void> addLocalDatasourceWithType(
      {required String p, required DatasourcePreviewType t, dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(p, serializer);
        sse_encode_datasource_preview_type(t, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kAddLocalDatasourceWithTypeConstMeta,
      argValues: [p, t],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kAddLocalDatasourceWithTypeConstMeta => const TaskConstMeta(
        debugName: "add_local_datasource_with_type",
        argNames: ["p", "t"],
      );

  @override
  Future<int> addS3Datasource(
      {required String endpoint,
      required String bucketname,
      required String accessKey,
      required String sessionKey,
      String? sessionToken,
      required String region,
      dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(endpoint, serializer);
        sse_encode_String(bucketname, serializer);
        sse_encode_String(accessKey, serializer);
        sse_encode_String(sessionKey, serializer);
        sse_encode_opt_String(sessionToken, serializer);
        sse_encode_String(region, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_i_64,
        decodeErrorData: null,
      ),
      constMeta: kAddS3DatasourceConstMeta,
      argValues: [
        endpoint,
        bucketname,
        accessKey,
        sessionKey,
        sessionToken,
        region
      ],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kAddS3DatasourceConstMeta => const TaskConstMeta(
        debugName: "add_s3_datasource",
        argNames: [
          "endpoint",
          "bucketname",
          "accessKey",
          "sessionKey",
          "sessionToken",
          "region"
        ],
      );

  @override
  Future<void> addS3DatasourceWithType(
      {required String endpoint,
      required String bucketname,
      required String accessKey,
      required String sessionKey,
      String? sessionToken,
      required String region,
      required DatasourcePreviewType t,
      dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(endpoint, serializer);
        sse_encode_String(bucketname, serializer);
        sse_encode_String(accessKey, serializer);
        sse_encode_String(sessionKey, serializer);
        sse_encode_opt_String(sessionToken, serializer);
        sse_encode_String(region, serializer);
        sse_encode_datasource_preview_type(t, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kAddS3DatasourceWithTypeConstMeta,
      argValues: [
        endpoint,
        bucketname,
        accessKey,
        sessionKey,
        sessionToken,
        region,
        t
      ],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kAddS3DatasourceWithTypeConstMeta => const TaskConstMeta(
        debugName: "add_s3_datasource_with_type",
        argNames: [
          "endpoint",
          "bucketname",
          "accessKey",
          "sessionKey",
          "sessionToken",
          "region",
          "t"
        ],
      );

  @override
  Future<List<Entry>> listObjectsByIndex(
      {required int index, required String p, dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_usize(index, serializer);
        sse_encode_String(p, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_entry,
        decodeErrorData: null,
      ),
      constMeta: kListObjectsByIndexConstMeta,
      argValues: [index, p],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kListObjectsByIndexConstMeta => const TaskConstMeta(
        debugName: "list_objects_by_index",
        argNames: ["index", "p"],
      );

  @override
  Future<List<Entry>> listObjectsLeft({required String p, dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(p, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_entry,
        decodeErrorData: null,
      ),
      constMeta: kListObjectsLeftConstMeta,
      argValues: [p],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kListObjectsLeftConstMeta => const TaskConstMeta(
        debugName: "list_objects_left",
        argNames: ["p"],
      );

  @override
  Future<List<Entry>> listObjectsRight({required String p, dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(p, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_entry,
        decodeErrorData: null,
      ),
      constMeta: kListObjectsRightConstMeta,
      argValues: [p],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kListObjectsRightConstMeta => const TaskConstMeta(
        debugName: "list_objects_right",
        argNames: ["p"],
      );

  @override
  Future<String> transferBetweenTwoDatasource(
      {required String p,
      required String savePath,
      required bool autoEncrypt,
      dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(p, serializer);
        sse_encode_String(savePath, serializer);
        sse_encode_bool(autoEncrypt, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kTransferBetweenTwoDatasourceConstMeta,
      argValues: [p, savePath, autoEncrypt],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kTransferBetweenTwoDatasourceConstMeta =>
      const TaskConstMeta(
        debugName: "transfer_between_two_datasource",
        argNames: ["p", "savePath", "autoEncrypt"],
      );

  @override
  Future<void> transferFromLeftToRight(
      {required int leftIndex,
      required int rightIndex,
      required String p,
      required String savePath,
      required bool autoEncrypt,
      dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_usize(leftIndex, serializer);
        sse_encode_usize(rightIndex, serializer);
        sse_encode_String(p, serializer);
        sse_encode_String(savePath, serializer);
        sse_encode_bool(autoEncrypt, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kTransferFromLeftToRightConstMeta,
      argValues: [leftIndex, rightIndex, p, savePath, autoEncrypt],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kTransferFromLeftToRightConstMeta => const TaskConstMeta(
        debugName: "transfer_from_left_to_right",
        argNames: ["leftIndex", "rightIndex", "p", "savePath", "autoEncrypt"],
      );

  @override
  Future<bool> checkAccountAvailable(
      {required String endpoint,
      required String bucketname,
      required String accessKey,
      required String sessionKey,
      String? sessionToken,
      required String region,
      dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(endpoint, serializer);
        sse_encode_String(bucketname, serializer);
        sse_encode_String(accessKey, serializer);
        sse_encode_String(sessionKey, serializer);
        sse_encode_opt_String(sessionToken, serializer);
        sse_encode_String(region, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCheckAccountAvailableConstMeta,
      argValues: [
        endpoint,
        bucketname,
        accessKey,
        sessionKey,
        sessionToken,
        region
      ],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kCheckAccountAvailableConstMeta => const TaskConstMeta(
        debugName: "check_account_available",
        argNames: [
          "endpoint",
          "bucketname",
          "accessKey",
          "sessionKey",
          "sessionToken",
          "region"
        ],
      );

  @override
  Future<void> downloadFromS3(
      {required String p, required String obj, dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(p, serializer);
        sse_encode_String(obj, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kDownloadFromS3ConstMeta,
      argValues: [p, obj],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kDownloadFromS3ConstMeta => const TaskConstMeta(
        debugName: "download_from_s3",
        argNames: ["p", "obj"],
      );

  @override
  Future<String?> generatePregisnUrl(
      {required String endpoint,
      required String bucketname,
      required String accessKey,
      required String sessionKey,
      String? sessionToken,
      required String region,
      required String obj,
      dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(endpoint, serializer);
        sse_encode_String(bucketname, serializer);
        sse_encode_String(accessKey, serializer);
        sse_encode_String(sessionKey, serializer);
        sse_encode_opt_String(sessionToken, serializer);
        sse_encode_String(region, serializer);
        sse_encode_String(obj, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kGeneratePregisnUrlConstMeta,
      argValues: [
        endpoint,
        bucketname,
        accessKey,
        sessionKey,
        sessionToken,
        region,
        obj
      ],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kGeneratePregisnUrlConstMeta => const TaskConstMeta(
        debugName: "generate_pregisn_url",
        argNames: [
          "endpoint",
          "bucketname",
          "accessKey",
          "sessionKey",
          "sessionToken",
          "region",
          "obj"
        ],
      );

  @override
  Future<void> initS3Client(
      {required String endpoint,
      required String bucketname,
      required String accessKey,
      required String sessionKey,
      String? sessionToken,
      required String region,
      dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(endpoint, serializer);
        sse_encode_String(bucketname, serializer);
        sse_encode_String(accessKey, serializer);
        sse_encode_String(sessionKey, serializer);
        sse_encode_opt_String(sessionToken, serializer);
        sse_encode_String(region, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kInitS3ClientConstMeta,
      argValues: [
        endpoint,
        bucketname,
        accessKey,
        sessionKey,
        sessionToken,
        region
      ],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kInitS3ClientConstMeta => const TaskConstMeta(
        debugName: "init_s3_client",
        argNames: [
          "endpoint",
          "bucketname",
          "accessKey",
          "sessionKey",
          "sessionToken",
          "region"
        ],
      );

  @override
  Future<List<Entry>> listObjects(
      {required String endpoint,
      required String bucketname,
      required String accessKey,
      required String sessionKey,
      String? sessionToken,
      required String region,
      required String path,
      required bool useGlobal,
      dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(endpoint, serializer);
        sse_encode_String(bucketname, serializer);
        sse_encode_String(accessKey, serializer);
        sse_encode_String(sessionKey, serializer);
        sse_encode_opt_String(sessionToken, serializer);
        sse_encode_String(region, serializer);
        sse_encode_String(path, serializer);
        sse_encode_bool(useGlobal, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_entry,
        decodeErrorData: null,
      ),
      constMeta: kListObjectsConstMeta,
      argValues: [
        endpoint,
        bucketname,
        accessKey,
        sessionKey,
        sessionToken,
        region,
        path,
        useGlobal
      ],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kListObjectsConstMeta => const TaskConstMeta(
        debugName: "list_objects",
        argNames: [
          "endpoint",
          "bucketname",
          "accessKey",
          "sessionKey",
          "sessionToken",
          "region",
          "path",
          "useGlobal"
        ],
      );

  @override
  Future<void> uploadToS3(
      {required String p, required String obj, dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(p, serializer);
        sse_encode_String(obj, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kUploadToS3ConstMeta,
      argValues: [p, obj],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kUploadToS3ConstMeta => const TaskConstMeta(
        debugName: "upload_to_s3",
        argNames: ["p", "obj"],
      );

  @override
  Future<void> uploadToS3WithConfig(
      {required String endpoint,
      required String bucketname,
      required String accessKey,
      required String sessionKey,
      String? sessionToken,
      required String region,
      required String p,
      required String obj,
      dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(endpoint, serializer);
        sse_encode_String(bucketname, serializer);
        sse_encode_String(accessKey, serializer);
        sse_encode_String(sessionKey, serializer);
        sse_encode_opt_String(sessionToken, serializer);
        sse_encode_String(region, serializer);
        sse_encode_String(p, serializer);
        sse_encode_String(obj, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kUploadToS3WithConfigConstMeta,
      argValues: [
        endpoint,
        bucketname,
        accessKey,
        sessionKey,
        sessionToken,
        region,
        p,
        obj
      ],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kUploadToS3WithConfigConstMeta => const TaskConstMeta(
        debugName: "upload_to_s3_with_config",
        argNames: [
          "endpoint",
          "bucketname",
          "accessKey",
          "sessionKey",
          "sessionToken",
          "region",
          "p",
          "obj"
        ],
      );

  @override
  String greet({required String name, dynamic hint}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kGreetConstMeta,
      argValues: [name],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kGreetConstMeta => const TaskConstMeta(
        debugName: "greet",
        argNames: ["name"],
      );

  @override
  Future<void> initApp({dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kInitAppConstMeta,
      argValues: [],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Stream<String> nativeMessageStream({dynamic hint}) {
    return handler.executeStream(StreamTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kNativeMessageStreamConstMeta,
      argValues: [],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kNativeMessageStreamConstMeta => const TaskConstMeta(
        debugName: "native_message_stream",
        argNames: [],
      );

  @override
  Future<void> testEncrypt({dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kTestEncryptConstMeta,
      argValues: [],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kTestEncryptConstMeta => const TaskConstMeta(
        debugName: "test_encrypt",
        argNames: [],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DatasourcePreviewType dco_decode_datasource_preview_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DatasourcePreviewType.values[raw as int];
  }

  @protected
  EncryptItem dco_decode_encrypt_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return EncryptItem(
      filePath: dco_decode_String(arr[0]),
      fileId: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  Entry dco_decode_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Entry(
      type: dco_decode_entry_type(arr[0]),
      path: dco_decode_String(arr[1]),
    );
  }

  @protected
  EntryType dco_decode_entry_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EntryType.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64OrU64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<EncryptItem> dco_decode_list_encrypt_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_encrypt_item).toList();
  }

  @protected
  List<Entry> dco_decode_list_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_entry).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  int dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64OrU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DatasourcePreviewType sse_decode_datasource_preview_type(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DatasourcePreviewType.values[inner];
  }

  @protected
  EncryptItem sse_decode_encrypt_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_filePath = sse_decode_String(deserializer);
    var var_fileId = sse_decode_i_64(deserializer);
    return EncryptItem(filePath: var_filePath, fileId: var_fileId);
  }

  @protected
  Entry sse_decode_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_type = sse_decode_entry_type(deserializer);
    var var_path = sse_decode_String(deserializer);
    return Entry(type: var_type, path: var_path);
  }

  @protected
  EntryType sse_decode_entry_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return EntryType.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  int sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<EncryptItem> sse_decode_list_encrypt_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EncryptItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_encrypt_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<Entry> sse_decode_list_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Entry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_entry(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint64();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError(
        'The type Delegate(AnyhowException) is not yet supported in serialized mode, please use full_dep mode, and feel free to create an issue');
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_datasource_preview_type(
      DatasourcePreviewType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_encrypt_item(EncryptItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.filePath, serializer);
    sse_encode_i_64(self.fileId, serializer);
  }

  @protected
  void sse_encode_entry(Entry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_entry_type(self.type, serializer);
    sse_encode_String(self.path, serializer);
  }

  @protected
  void sse_encode_entry_type(EntryType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_encrypt_item(
      List<EncryptItem> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_encrypt_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_entry(List<Entry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint64(self);
  }
}
