// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.21.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Entry {
  final EntryType type;
  final String path;

  const Entry({
    required this.type,
    required this.path,
  });

  @override
  int get hashCode => type.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Entry &&
          runtimeType == other.runtimeType &&
          type == other.type &&
          path == other.path;
}

enum EntryType {
  file,
  folder,
}
