[package]
name = "native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
anyhow = "1"
aes-gcm-siv = "0.11.1"
flutter_rust_bridge = "= 1.82.6"

[build-dependencies]
flutter_rust_bridge_codegen = "= 1.82.6"