// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.21.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../process/datasource.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> transferFromLeftToRight(
        {required int leftIndex,
        required int rightIndex,
        required String p,
        required String savePath,
        required bool autoEncrypt,
        dynamic hint}) =>
    RustLib.instance.api.transferFromLeftToRight(
        leftIndex: leftIndex,
        rightIndex: rightIndex,
        p: p,
        savePath: savePath,
        autoEncrypt: autoEncrypt,
        hint: hint);

Future<int> addLocalDatasource({required String p, dynamic hint}) =>
    RustLib.instance.api.addLocalDatasource(p: p, hint: hint);

Future<int> addS3Datasource(
        {required String endpoint,
        required String bucketname,
        required String accessKey,
        required String sessionKey,
        String? sessionToken,
        required String region,
        dynamic hint}) =>
    RustLib.instance.api.addS3Datasource(
        endpoint: endpoint,
        bucketname: bucketname,
        accessKey: accessKey,
        sessionKey: sessionKey,
        sessionToken: sessionToken,
        region: region,
        hint: hint);

Future<List<Entry>> listObjectsByIndex(
        {required int index, required String p, dynamic hint}) =>
    RustLib.instance.api.listObjectsByIndex(index: index, p: p, hint: hint);
